version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"                      
    volumes:
      - mariadb_data:/var/lib/mysql      
    networks:
      - mariadb_network

volumes:
  mariadb_data:                          # Named volume for persistent storage

networks:
  mariadb_network:                       # Dedicated network for MariaDB